### ISSUE TITLE
通过fastchat部署本地模型遇到的问题

### ISSUE THREAD

**Issue by YinSonglin1997** [THUDM/AgentBench#146]
您好，我使用fastchat进行加载chatglm3-6b模型，
step1 `python3 -m fastchat.serve.controller`
step2 `python3 -m fastchat.serve.model_worker --model-path /ldata/llms/chatglm3-6b`
step3 `python3 -m fastchat.serve.openai_api_server --host 10.0.1.227 --port 30008`
启动服务后，我修改了fs_agents.yaml文件，内容为
```
default:
  module: "src.client.agents.FastChatAgent"
  parameters:
    name: "FastChat"
    controller_address: "http://10.0.1.227:30008"
    max_new_tokens: 512
    temperature: 0

chatglm3-6b:
  parameters:
    model_name: "chatglm3-6b"
```
然后运行 python -m src.client.agent_test --config configs/agents/fs_agents.yaml --agent chatglm3-6b
接着新开了一个终端运行命令 python -m src.start_task -a，此时报错
`mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:16018' (111)`
请问这个问题怎么解决？还有请问我的步骤以及yaml文件有问题吗？期待您的回复！

**Comment by lambda7xx** [comment]
你这个问题解决了吗

**Comment by YinSonglin1997** [comment]
controller_address地址写错了，改为`python3 -m fastchat.serve.controller`的地址；
将configs/assignments/default.yaml中agent名字修改。

**Comment by lambda7xx** [comment]
那这个python3 -m fastchat.serve.controller的地址，是多少

**Comment by lambda7xx** [comment]
这个control-address我这里应该是http://localhost:21002
![image](https://github.com/user-attachments/assets/6e1f88c5-94c3-4a52-af7b-eb95e23c1599)
那python3 -m fastchat.serve.openai_api_server --host 10.0.1.227 --port 30008这个应该怎么搞,host和port不变吗

**Comment by YinSonglin1997** [comment]
> 这个control-address我这里应该是http://localhost:21002 ![image](https://private-user-images.githubusercontent.com/35867865/350304771-6e1f88c5-94c3-4a52-af7b-eb95e23c1599.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzc5ODgsIm5iZiI6MTcyMTM3NzY4OCwicGF0aCI6Ii8zNTg2Nzg2NS8zNTAzMDQ3NzEtNmUxZjg4YzUtOTRjMy00YTUyLWFmN2ItZWI5NWUyM2MxNTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA4MjgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhODE3MzQyNWY5MmNkOTAyNTNkNjJjZmVhNjNlN2UwOTBhYTRiYjBiZmFiMmNlMzM5ZjAyN2EzODM5OWRlYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jglSN4r3n-2vjmqP_Ir4FHKWpR2V6VmOkaNykkIco2U) 那python3 -m fastchat.serve.openai_api_server --host 10.0.1.227 --port 30008这个应该怎么搞,host和port不变吗

host是你服务器的地址，port你可以自定义

**Comment by lambda7xx** [comment]
我试了下llama3-8b

1 terminal 1: python3 -m fastchat.serve.controller
2 terminal 2:python3 -m fastchat.serve.model_worker --model-path /data/llama3/Meta-Llama-3-8B-hf
3 termain 3: python3 -m fastchat.serve.openai_api_server --host 127.0.0.1 --port 30008
4 fs_agent.yaml
```
default:
  module: "src.client.agents.FastChatAgent"
  parameters:
    name: "FastChat"
    controller_address: "http://localhost:21002"
    max_new_tokens: 512
    temperature: 0

vicuna-33b:
  parameters:
    model_name: "vicuna-33b-v1.3"

wizard-30b:
  parameters:
    model_name: "WizardLM-30B-V1.0-merged"

vicuna-13b:
  parameters:
    model_name: "vicuna-13b-v1.5"

vicuna-7b:
  parameters:
    model_name: "vicuna-7b-v1.5"

llama3-8b:
  parameters:
    model_name: "llama3-8b"



```
5 terminal 4: python -m src.client.agent_test --config configs/agents/fs_agent.yaml --agent llama3-8b

6 terminal 5: python -m src.start_task -a

7 termina 6:python -m src.assigner

报错

```
/home/xxxx/anaconda3/envs/agent-bench/lib/python3.9/site-packages/transformers/utils/generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/home/xxxx/anaconda3/envs/agent-bench/lib/python3.9/site-packages/transformers/utils/generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "/home/xxxx/anaconda3/envs/agent-bench/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxxx/anaconda3/envs/agent-bench/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xxxx/AgentBench/src/assigner.py", line 422, in <module>
    value = AssignmentConfig.post_validate(value)
  File "/home/xxxx/AgentBench/src/typings/config.py", line 79, in post_validate
    assert (
AssertionError: Agent llam3-8b is not defined.
```

**Comment by YinSonglin1997** [comment]
configs/assignments/default.yaml中agent名字改掉了吗？

**Comment by lambda7xx** [comment]
configs/assignments/default.yaml是要改成这样吗
```
import: definition.yaml

concurrency:
  task:
    dbbench-std: 5
    os-std: 5
  agent:
    llama3-8b: 5 #todo(xiao):this can changed to other models 

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - llama3-8b #todo(xiao):this can changed to other models 
    task:
      - dbbench-std
      - os-std

output: "outputs/{TIMESTAMP}"

```
