### ISSUE TITLE
how to run the webshop task

### ISSUE THREAD

**Issue by Z-ZHHH** [THUDM/AgentBench#41]
I want to run the webshop task, and I have run the following cmds
```
pip install --upgrade pip
pip install -r requirements.txt
bash scripts/build_docker.sh
```
However, there are still some third-party libraries not installed, i.e., faiss.  In [tutorial](https://github.com/THUDM/AgentBench/blob/main/docs/tutorial.md#how-to-run-all-tasks-in-agentbench), it seems not mentioned. Have I missed sth.?

**Comment by zhc7** [comment]
Hi, we recommend you to use our prebuilt image. Setting up an environment for task can be frustrating and boring. If you insist to build on your own, you should refer to src/tasks/webshop/README.md.

**Comment by Z-ZHHH** [comment]
Thanks for your reply! 
I have run all the installation cmds in the tutorial. 
Now I activate my conda environment. Is the step as follows?
1. python create_assignment.py  --assignment configs/assignments/my_example.yaml
2. bash .assignment/xxxx.sh

Should I start the docker and run the cmds in the docker? I am kind of confused. Wish for you reply, thx!

Here is my my_example.yaml:
```
default:
    agent: configs/agents/api_agents/llama2-7b.yaml
    task:
        parameters:
        workers: 15
assignments:
    - task:
        from: "configs/tasks/webshop/dev.yaml"
        parameters:
            workers: 6
    - task: "configs/tasks/card_game/dev.yaml"
```
