### ISSUE TITLE
Custom task or test set

### ISSUE THREAD

**Issue by mahmoudialireza** [THUDM/AgentBench#44]
Hello Team
Is it possible to create a customized test set for a specific task (for example for medical or financial) and use this tool to evaluate fine tune models?
Thanks in advance.

**Comment by zhc7** [comment]
Yes. We are working on a newer version of the framework for easier deployment and extension.

**Comment by mahmoudialireza** [comment]
Thanks. For now how can I do that? IS there any documentation or instruction for that?

**Comment by Xiao9905** [comment]
@mahmoudialireza Hi, thanks for your interest in AgentBench. Our new version v0.2 has been updated to the repo and please take a look at our readme to find the new documentation. Feel free to reopen this issue if you need further help.

**Comment by chiyuzhang94** [comment]
Hi @Xiao9905 @zhc7 ,

I wonder how to add new task into AgentBench. Could you point me where the guide for adding new dataset/task?

Thanks.

**Comment by zhc7** [comment]
Hi @chiyuzhang94 I just add the guide: https://github.com/THUDM/AgentBench/blob/main/docs/Extension_en.md

**Comment by chiyuzhang94** [comment]
> Hi @chiyuzhang94 I just added the guide: https://github.com/THUDM/AgentBench/blob/main/docs/Extension_en.md

Hi @zhc7 ,

I have prepared the task.py script for my new task. I also created a new yaml file for my new task and tried to run the task with `python -m src.assigner --config configs/assignments/new_task` but I got this error:

```
  File "/home/AgentBench/src/typings/config.py", line 83, in post_validate
    assert (
AssertionError: Task new_task is not defined.
```
I wonder where I should define the task.

**Comment by zhc7** [comment]
Hi @chiyuzhang94 , your steps are correct. Can you show me your config yamls? Including task_assembly.yaml and all the yaml you added or modified.

**Comment by chiyuzhang94** [comment]
> Hi @chiyuzhang94 , your steps are correct. Can you show me your config yamls? Including task_assembly.yaml and all the yaml you added or modified.

Thanks. Here they are

AgentBench/configs/assignments/spam_email.yaml
```
import: definition.yaml

concurrency:
  task:
    spam_email: 5
  agent:
    gpt-3.5-turbo: 5

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - gpt-3.5-turbo
    task:
      - spam_email

output: "outputs/{TIMESTAMP}"

```

AgentBench/configs/tasks/spam_email.yaml
```
default:
  module: src.server.tasks.spam_email.SpamEmail
  parameters:
    data_path: "data/spam_email/"
    max_step: 5
```

task_assembly.yaml
```
default:
  docker:
    command: umask 0; [ -f /root/.setup.sh ] && bash /root/.setup.sh;

import:
  - webshop.yaml
  - dbbench.yaml
  - mind2web.yaml
  - card_game.yaml
  - kg.yaml
  - os.yaml
  - ltp.yaml
  - alfworld.yaml
  - avalon.yaml
  - spam_email.yaml
```
