### ISSUE TITLE
INTERACT_FAILED Error: Session does not exist

### ISSUE THREAD

**Issue by glad4enkonm** [THUDM/AgentBench#70]
**Can not start a KG task with vicuna-7b**
Getting NTERACT_FAILED Error: Session does not exist
What can be the reason?

**To Reproduce**
1. configs/start_task.yaml
```
definition:
  import: tasks/task_assembly.yaml

start:
  kg-std: 1
```

2. configs/assignments/default.yaml
```
import: definition.yaml

concurrency:
  task:
    kg-std: 1
  agent:
    vicuna-7b: 1

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - vicuna-7b
    task:
      - kg-std

output: "outputs/{TIMESTAMP}"

```
3. Running Vicuna 7b on cpu 8bit, starting the 
4. python -m src.start_task -a
5. python -m src.assigner
6. outputs/2023-11-07-22-36-41/vicuna-7b/kg-std/error.jsonl

```
{"index": 149, "error": "INTERACT_FAILED", "info": "{\"detail\":\"Error: Session does not exist\"}", "output": {"index": null, "status": "running", "result": null, "history": null}, "time": {"timestamp": 1699397194471, "str": "2023-11-07 22:46:34"}}
{"index": 148, "error": "INTERACT_FAILED", "info": "{\"detail\":\"Error: Session does not exist\"}", "output": {"index": null, "status": "running", "result": null, "history": null}, "time": {"timestamp": 1699398002162, "str": "2023-11-07 23:00:02"}}
{"index": 147, "error": "INTERACT_FAILED", "info": "{\"detail\":\"Error: Session does not exist\"}", "output": {"index": null, "status": "running", "result": null, "history": null}, "time": {"timestamp": 1699398438856, "str": "2023-11-07 23:07:18"}}
```

outputs/2023-11-07-22-36-41/config.yaml

```
assignments:
- agent: vicuna-7b
  task: kg-std
concurrency:
  agent:
    vicuna-7b: 1
  task:
    kg-std: 1
definition:
  agent:
    vicuna-7b:
      module: src.client.agents.FastChatAgent
      parameters:
        controller_address: http://localhost:21001
        max_new_tokens: 512
        model_name: vicuna-7b-v1.5
        name: FastChat
        temperature: 0
  task:
    kg-std:
      module: src.client.TaskClient
      parameters:
        controller_address: http://localhost:5000/api
        data_file: data/knowledgegraph/std.json
        name: KnowledgeGraph-std
        round: 15
        sparql_url: http://164.107.116.56:3093/sparql
output: outputs/2023-11-07-22-36-41
```

**Screenshots or Terminal Copy&Paste**
![image](https://github.com/THUDM/AgentBench/assets/11142000/95c8de10-d4ca-4c58-bd63-f73dc013a94f)
