### ISSUE TITLE
游戏任务启动失败[Bug/Assistance] 

### ISSUE THREAD

**Issue by smartliuhw** [THUDM/AgentBench#96]
我想要评测游戏的三个任务，在配置了``start_task.yaml``后，一直显示task不存在，麻烦问一下可以怎么解决

报错：
<img width="1508" alt="image" src="https://github.com/THUDM/AgentBench/assets/79445290/a2a68ed3-a175-44c9-b1dd-2f395209724f">

start_task.yaml
```yaml
definition:
  import: tasks/task_assembly.yaml

start:
  # dbbench-std: 5
  # os-std: 5
  cg-std: 5
  alfworld-std: 5
  ltp-std: 5
```

default.yaml
```yaml
import: definition.yaml

concurrency:
  task:
    # dbbench-std: 5
    # os-std: 5
    cg-std: 5
    alfworld-std: 5
    ltp-std: 5
  agent:
    phi: 5

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - phi
    task:
      # - dbbench-std
      # - os-std
      - cg-std
      - alfworld-std
      - ltp-std

output: "outputs/{TIMESTAMP}"
```
